import React from "react";
import "./globals.css";
import type { Metadata } from "next";
import Nav from "@/components/Nav";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Toaster from "@/components/Toaster";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    auth,
}: Readonly<{
    children: React.ReactNode;
    auth: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                <div className="flex flex-col h-screen max-h-screen">
                    <Nav />
                    <div className="flex-grow overflow-y-auto bg-page text-default-text">
                        {children}
                    </div>
                    <Toaster />
                </div>
                {auth}
            </body>
        </html>
    );
}
