import styles from "./styles.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About Next App",
    description: "Generated by create next app",
};
export default function AboutLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <h1>standard page layout</h1>
            <main className={styles.main}>{children}</main>
        </>
    );
}
